model:
  num_classes: 10
  class_emb_size: 4 
  sample_size: 28 # the target image resolution
  in_channels: 1 # Additional input channels for class cond.
  out_channels: 1 # the number of output channels
  layers_per_block: 2 # how many ResNet layers to use per UNet block
  block_out_channels: [32, 64, 64]
  down_block_types:
    - "DownBlock2D" # a regular ResNet downsampling block
    - "AttnDownBlock2D" # a ResNet downsampling block with spatial self-attention
    - "AttnDownBlock2D"
  up_block_types:
    - "UpBlock2D"
    - "AttnUpBlock2D" # a ResNet upsampling block with spatial self-attention
    - "AttnUpBlock2D" # a regular ResNet upsampling block

dataset:
  root: "mnist/"
  batch_size: 128
  shuffle: True
  download: True

training:
  n_epochs: 10
  lr: 1e-2

device:
  use_mps: true
  use_cuda: true

scheduler:
  num_train_timesteps: 50
  beta_schedule: "squaredcos_cap_v2"

logging:
  tensorboard_dir: "../runs"
  experimentID: "exp-23"
  artifact_save_path: "../mnist_diffusion_experiments"